// SPDX-License-Identifier: AGPL-3.0-only
// Copyright 2026 Artur Abalov
// Generated by `npm run gen:api` from src/api/openapi.json. Do not edit.

export interface paths {
    "/api/v1/sources/{sourceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Source card */
        get: operations["getSource"];
        /**
         * Replace a source
         * @description The same 422 codes as creation.
         */
        put: operations["replaceSource"];
        post?: never;
        /**
         * Delete a source
         * @description Its runs and snapshots stay in the history.
         */
        delete: operations["deleteSource"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List sources */
        get: operations["listSources"];
        put?: never;
        /**
         * Create a source
         * @description 422 codes: unknown_agent, unknown_plugin, unknown_repository, invalid_config, validation_failed.
         */
        post: operations["createSource"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources/{sourceId}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Back up the source now
         * @description Queues a manual backup run; it waits for an offline agent. One active run per source (D6).
         */
        post: operations["startRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current session
         * @description 401 when there is none or it expired.
         */
        get: operations["getSession"];
        put?: never;
        /**
         * Sign in
         * @description Sets the session cookie. The same answer for any wrong password.
         */
        post: operations["createSession"];
        /**
         * Sign out
         * @description Ends the session and clears the cookie.
         */
        delete: operations["deleteSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/enrollment-tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List tokens
         * @description Newest first.
         */
        get: operations["listEnrollmentTokens"];
        put?: never;
        /**
         * Create a token
         * @description The token string and command are in this response only.
         */
        post: operations["createEnrollmentToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/enrollment-tokens/{tokenId}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke a token
         * @description Revoking a revoked token is a no-op and answers 200.
         */
        post: operations["revokeEnrollmentToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Server status
         * @description Public: the dashboard shows it before sign-in.
         */
        get: operations["status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources/{sourceId}/snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Snapshots of the source
         * @description Newest first.
         */
        get: operations["listSourceSnapshots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List runs
         * @description Newest first. Filters combine with AND; status values with OR.
         */
        get: operations["listRuns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{runId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run card with steps */
        get: operations["getRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{runId}/steps/{stepId}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Log of a step
         * @description Lines with seq > afterSeq, oldest first.
         */
        get: operations["listStepLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/enrollment-tokens/{tokenId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Token card */
        get: operations["getEnrollmentToken"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List agents */
        get: operations["listAgents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/{agentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Agent card */
        get: operations["getAgent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description What to back up, where from and where to */
        SourceInput: {
            name: string;
            /** Format: uuid */
            agentId: string;
            /** @description A plugin the agent offers */
            plugin: string;
            /** @description A repository from the agent's last Register; its snapshots live there */
            repositoryName: string;
            /** @description Plugin config, valid against the plugin's configSchema; secrets by name only */
            config: {
                [key: string]: unknown;
            };
        };
        /** @enum {string} */
        ErrorCode: "unauthenticated" | "too_many_attempts" | "not_found" | "validation_failed" | "unknown_agent" | "unknown_plugin" | "unknown_repository" | "invalid_config" | "run_active" | "token_used" | "token_expired" | "not_implemented";
        /** @description An error (RFC 9457) */
        Problem: {
            /** @description URI reference identifying the problem type; about:blank when the status says it all */
            type: string;
            /** @description Short summary for people; not for matching, use code */
            title: string;
            /**
             * Format: int32
             * @description HTTP status code
             */
            status: number;
            /** @description Explanation of this occurrence; null when the title says it all */
            detail: string | null;
            code: components["schemas"]["ErrorCode"];
        };
        /** @description A field of the request that failed validation */
        FieldError: {
            /** @description JSON name of the field, e.g. repositoryName */
            field: string;
            /** @description Why the value was rejected */
            message: string;
        };
        /** @description The request is well-formed but its values are not acceptable (RFC 9457) */
        ValidationProblem: {
            /** @description URI reference identifying the problem type; about:blank when the status says it all */
            type: string;
            /** @description Short summary for people; not for matching, use code */
            title: string;
            /**
             * Format: int32
             * @description HTTP status code
             */
            status: number;
            /** @description Explanation of this occurrence; null when the title says it all */
            detail: string | null;
            code: components["schemas"]["ErrorCode"];
            /** @description The rejected fields */
            errors: components["schemas"]["FieldError"][];
        };
        /** @description A backup source */
        Source: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: uuid */
            agentId: string;
            plugin: string;
            /** @description A repository from the agent's last Register; its snapshots live there */
            repositoryName: string;
            /** @description Plugin config, valid against the plugin's configSchema; secrets by name only */
            config: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        /** @description The source already has an active run (D6); no new run was created (RFC 9457) */
        RunActiveProblem: {
            /** @description URI reference identifying the problem type; about:blank when the status says it all */
            type: string;
            /** @description Short summary for people; not for matching, use code */
            title: string;
            /**
             * Format: int32
             * @description HTTP status code
             */
            status: number;
            /** @description Explanation of this occurrence; null when the title says it all */
            detail: string | null;
            /** @description run_active */
            code: components["schemas"]["ErrorCode"];
            /**
             * Format: uuid
             * @description The run that is queued, dispatched or running
             */
            activeRunId: string;
        };
        /** @description What a backup step produced */
        BackupOutput: {
            /** @description restic snapshot id */
            snapshotId: string;
            /** Format: int64 */
            totalBytes: number;
            /** Format: int64 */
            addedBytes: number;
        };
        /** @description A run with its steps */
        Run: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            sourceId: string;
            /** Format: uuid */
            agentId: string;
            trigger: components["schemas"]["RunTrigger"];
            status: components["schemas"]["RunStatus"];
            /** @description Why it failed, was rejected or lost; null on success */
            message: string | null;
            /** Format: date-time */
            queuedAt: string;
            /** Format: date-time */
            startedAt: string | null;
            /** Format: date-time */
            finishedAt: string | null;
            steps: components["schemas"]["RunStep"][];
        };
        /** @enum {string} */
        RunStatus: "queued" | "dispatched" | "running" | "succeeded" | "failed" | "cancelled";
        /** @description One command to the agent */
        RunStep: {
            /**
             * Format: uuid
             * @description Also the command_id of the agent protocol
             */
            id: string;
            /** Format: int32 */
            ordinal: number;
            action: components["schemas"]["StepAction"];
            status: components["schemas"]["StepStatus"];
            /** @description Last reported phase; null before the agent accepts the step */
            phase: components["schemas"]["StepPhase"] | null;
            /** Format: uuid */
            agentId: string;
            /**
             * Format: uuid
             * @description null for action run
             */
            sourceId: string | null;
            plugin: string;
            /** @description null for action run */
            repositoryName: string | null;
            /** Format: int64 */
            bytesProcessed: number | null;
            /**
             * Format: int64
             * @description null while unknown
             */
            bytesTotal: number | null;
            /** @description Why it failed, was rejected or lost; null on success */
            message: string | null;
            /** @description Set when a backup step succeeded */
            backup: components["schemas"]["BackupOutput"] | null;
            /** Format: date-time */
            queuedAt: string;
            /** Format: date-time */
            dispatchedAt: string | null;
            /** Format: date-time */
            startedAt: string | null;
            /** Format: date-time */
            finishedAt: string | null;
        };
        /** @enum {string} */
        RunTrigger: "schedule" | "manual" | "verification";
        /** @enum {string} */
        StepAction: "backup" | "restore" | "verify" | "run";
        /** @enum {string} */
        StepPhase: "accepted" | "preparing" | "dumping" | "uploading" | "restoring" | "verifying";
        /** @enum {string} */
        StepStatus: "queued" | "dispatched" | "running" | "succeeded" | "failed" | "cancelled" | "timed_out" | "rejected" | "lost";
        /** @description Sign-in with the administrator password (D2) */
        SessionRequest: {
            /** @description The administrator password from the server's environment */
            password: string;
        };
        /** @description A new enrollment token */
        CreateEnrollmentTokenRequest: {
            /**
             * Format: int64
             * @description Lifetime in seconds: from 5 minutes to 7 days; 24 hours when omitted
             */
            ttlSeconds?: number | null;
        };
        /** @description A created token: the only response with the token string (docs/specs/enrollment-token.md) */
        CreatedEnrollmentToken: {
            /** Format: uuid */
            id: string;
            /** @description sard_<secret>.<CA fingerprint>; shown once, the server keeps only its hash */
            token: string;
            /** @description Ready-to-run command: sard-agent enroll --server <address> --token <token> */
            enrollCommand: string;
            /** Format: date-time */
            expiresAt: string;
        };
        /** @description The token can no longer be revoked (RFC 9457) */
        TokenConflictProblem: {
            /** @description URI reference identifying the problem type; about:blank when the status says it all */
            type: string;
            /** @description Short summary for people; not for matching, use code */
            title: string;
            /**
             * Format: int32
             * @description HTTP status code
             */
            status: number;
            /** @description Explanation of this occurrence; null when the title says it all */
            detail: string | null;
            /** @description token_used or token_expired */
            code: components["schemas"]["ErrorCode"];
            /**
             * Format: uuid
             * @description The agent enrolled with the token; set when code is token_used
             */
            agentId: string | null;
        };
        /** @description An enrollment token without its string */
        EnrollmentToken: {
            /** Format: uuid */
            id: string;
            status: components["schemas"]["EnrollmentTokenStatus"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            expiresAt: string;
            /**
             * Format: date-time
             * @description When an agent enrolled with it
             */
            usedAt: string | null;
            /** Format: date-time */
            revokedAt: string | null;
            /**
             * Format: uuid
             * @description The agent enrolled with it; set when status is used
             */
            agentId: string | null;
        };
        /** @enum {string} */
        EnrollmentTokenStatus: "active" | "used" | "expired" | "revoked";
        StatusResponse: {
            /** @description sard-server version */
            version: string;
            /**
             * Format: date-time
             * @description When a restore was last verified successfully; null if never
             */
            lastVerifiedRestoreAt: string | null;
        };
        /** @description A page of sources */
        SourcePage: {
            items: components["schemas"]["Source"][];
            /** @description Pass as cursor to get the next page; null on the last page */
            nextCursor: string | null;
        };
        /** @description A restic snapshot made by a run of the source */
        Snapshot: {
            /** Format: uuid */
            id: string;
            /** @description restic snapshot id */
            snapshotId: string;
            /** Format: uuid */
            sourceId: string;
            /** Format: uuid */
            runId: string;
            /** Format: uuid */
            stepId: string;
            /** Format: uuid */
            agentId: string;
            repositoryName: string;
            /** @description restic repository id; the same key held by several hosts shares it (ADR 0008) */
            repositoryId: string;
            /** Format: int64 */
            totalBytes: number;
            /** Format: int64 */
            addedBytes: number;
            /** Format: date-time */
            createdAt: string;
            /**
             * Format: date-time
             * @description When restic forget removed it; null while it exists
             */
            forgottenAt: string | null;
        };
        /** @description A page of snapshots */
        SnapshotPage: {
            items: components["schemas"]["Snapshot"][];
            /** @description Pass as cursor to get the next page; null on the last page */
            nextCursor: string | null;
        };
        /** @description The current administrator session */
        Session: {
            /**
             * Format: uuid
             * @description Tenant of the session; every other endpoint works within it
             */
            tenantId: string;
            /**
             * Format: date-time
             * @description When the session ends unless renewed
             */
            expiresAt: string;
        };
        /** @description A page of runs */
        RunPage: {
            items: components["schemas"]["RunSummary"][];
            /** @description Pass as cursor to get the next page; null on the last page */
            nextCursor: string | null;
        };
        /** @description A run in the list */
        RunSummary: {
            /** Format: uuid */
            id: string;
            /**
             * Format: uuid
             * @description The source the run backs up
             */
            sourceId: string;
            /**
             * Format: uuid
             * @description The source's agent
             */
            agentId: string;
            trigger: components["schemas"]["RunTrigger"];
            status: components["schemas"]["RunStatus"];
            /** @description Why it failed, was rejected or lost; null on success */
            message: string | null;
            /** Format: date-time */
            queuedAt: string;
            /** Format: date-time */
            startedAt: string | null;
            /** Format: date-time */
            finishedAt: string | null;
        };
        /** @enum {string} */
        LogLevel: "debug" | "info" | "warn" | "error";
        /** @description A line of a step's log */
        LogLine: {
            /**
             * Format: int64
             * @description Position in the step's log, assigned by the server; increasing, starts at 1
             */
            seq: number;
            /**
             * Format: date-time
             * @description Time on the agent
             */
            time: string;
            level: components["schemas"]["LogLevel"];
            /** @description Secret values are redacted by the agent */
            text: string;
        };
        /** @description Log lines after afterSeq, in seq order */
        LogPage: {
            items: components["schemas"]["LogLine"][];
            /**
             * Format: int64
             * @description Pass as afterSeq to continue: seq of the last line, or afterSeq when there are none
             */
            nextAfterSeq: number;
            /** @description More lines are there already; false is the end for now, poll to follow a step */
            hasMore: boolean;
        };
        /** @description A page of enrollment tokens */
        EnrollmentTokenPage: {
            items: components["schemas"]["EnrollmentToken"][];
            /** @description Pass as cursor to get the next page; null on the last page */
            nextCursor: string | null;
        };
        /** @enum {string} */
        AgentStatus: "online" | "offline";
        /** @description A page of agents */
        AgentPage: {
            items: components["schemas"]["AgentSummary"][];
            /** @description Pass as cursor to get the next page; null on the last page */
            nextCursor: string | null;
        };
        /** @description An agent in the list */
        AgentSummary: {
            /** Format: uuid */
            id: string;
            /** @description Host name reported at enrollment and on Register */
            hostname: string;
            status: components["schemas"]["AgentStatus"];
            /** @description sard-agent version; null until the first Register */
            agentVersion: string | null;
            /** @description GOOS of the agent, e.g. linux; null until the first Register */
            os: string | null;
            /** @description GOARCH of the agent, e.g. amd64; null until the first Register */
            arch: string | null;
            /** Format: date-time */
            registeredAt: string;
            /**
             * Format: date-time
             * @description Last heartbeat; null if the agent never connected
             */
            lastSeenAt: string | null;
            /**
             * Format: date-time
             * @description When its certificates were revoked; null if not revoked
             */
            revokedAt: string | null;
        };
        /** @description An agent with what it reported in its last Register */
        AgentDetails: {
            /** Format: uuid */
            id: string;
            hostname: string;
            status: components["schemas"]["AgentStatus"];
            agentVersion: string | null;
            os: string | null;
            arch: string | null;
            /** Format: date-time */
            registeredAt: string;
            /** Format: date-time */
            lastSeenAt: string | null;
            /** Format: date-time */
            revokedAt: string | null;
            /**
             * Format: int32
             * @description Protocol version of the last Register; null until the first one
             */
            protocolVersion: number | null;
            plugins: components["schemas"]["AgentPlugin"][];
            repositories: components["schemas"]["AgentRepository"][];
            /** @description Names of secrets defined on the host; values never leave it (ADR 0008) */
            secretNames: string[];
            /** @description Names of allowlisted scripts on the host; paths never leave it (ADR 0008) */
            scriptNames: string[];
        };
        /** @description A plugin the agent offers */
        AgentPlugin: {
            name: string;
            version: string;
            actions: components["schemas"]["StepAction"][];
            /** @description JSON Schema (draft 2020-12) of a source's config; secret fields hold a secret name */
            configSchema: {
                [key: string]: unknown;
            };
        };
        /** @description A restic repository defined on the agent host (ADR 0008); no credentials */
        AgentRepository: {
            /** @description Name a source refers to */
            name: string;
            /** @description Storage backend, e.g. local, sftp, s3 */
            backend: string;
            /** @description restic repository id; null while the repository is not initialized */
            repositoryId: string | null;
            /** @description crypto.Provider that hands the key to restic */
            cryptoProvider: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getSource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sourceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Source"];
                };
            };
            /** @description No session or it expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Not found in the session's tenant */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    replaceSource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sourceId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Source"];
                };
            };
            /** @description No session or it expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Not found in the session's tenant */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Rejected values; errors name the fields */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ValidationProblem"];
                };
            };
        };
    };
    deleteSource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sourceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No session or it expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Not found in the session's tenant */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description The source has an active run (D6) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RunActiveProblem"];
                };
            };
        };
    };
    listSources: {
        parameters: {
            query?: {
                agentId?: string;
                /** @description nextCursor of the previous page; omit for the first page */
                cursor?: string;
                /** @description Page size */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourcePage"];
                };
            };
            /** @description No session or it expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    createSource: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Source"];
                };
            };
            /** @description No session or it expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Rejected values; errors name the fields */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ValidationProblem"];
                };
            };
        };
    };
    startRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sourceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description No session or it expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Not found in the session's tenant */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description The source has an active run (D6) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RunActiveProblem"];
                };
            };
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            /** @description No session or it expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    createSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionRequest"];
            };
        };
        responses: {
            /** @description Signed in */
            204: {
                headers: {
                    /** @description sard_session; HttpOnly; SameSite=Strict */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Wrong password */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Too many failed attempts; sign-in is locked for a while */
            429: {
                headers: {
                    /** @description Seconds until the next attempt */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    deleteSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Signed out */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No session or it expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listEnrollmentTokens: {
        parameters: {
            query?: {
                status?: components["schemas"]["EnrollmentTokenStatus"];
                /** @description nextCursor of the previous page; omit for the first page */
                cursor?: string;
                /** @description Page size */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollmentTokenPage"];
                };
            };
            /** @description No session or it expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    createEnrollmentToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEnrollmentTokenRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedEnrollmentToken"];
                };
            };
            /** @description No session or it expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Rejected values; errors name the fields */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ValidationProblem"];
                };
            };
        };
    };
    revokeEnrollmentToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tokenId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollmentToken"];
                };
            };
            /** @description No session or it expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Not found in the session's tenant */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description The token was used (agentId names the agent) or expired */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["TokenConflictProblem"];
                };
            };
        };
    };
    status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
        };
    };
    listSourceSnapshots: {
        parameters: {
            query?: {
                /** @description nextCursor of the previous page; omit for the first page */
                cursor?: string;
                /** @description Page size */
                limit?: number;
            };
            header?: never;
            path: {
                sourceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotPage"];
                };
            };
            /** @description No session or it expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Not found in the session's tenant */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listRuns: {
        parameters: {
            query?: {
                sourceId?: string;
                agentId?: string;
                status?: components["schemas"]["RunStatus"][];
                /** @description nextCursor of the previous page; omit for the first page */
                cursor?: string;
                /** @description Page size */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunPage"];
                };
            };
            /** @description No session or it expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description No session or it expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Not found in the session's tenant */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listStepLogs: {
        parameters: {
            query?: {
                /** @description Return lines after this seq; 0 for the start */
                afterSeq?: number;
                /** @description Page size */
                limit?: number;
            };
            header?: never;
            path: {
                runId: string;
                stepId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogPage"];
                };
            };
            /** @description No session or it expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Not found in the session's tenant */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getEnrollmentToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tokenId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollmentToken"];
                };
            };
            /** @description No session or it expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Not found in the session's tenant */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listAgents: {
        parameters: {
            query?: {
                status?: components["schemas"]["AgentStatus"];
                /** @description nextCursor of the previous page; omit for the first page */
                cursor?: string;
                /** @description Page size */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentPage"];
                };
            };
            /** @description No session or it expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentDetails"];
                };
            };
            /** @description No session or it expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Not found in the session's tenant */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
}
