// SPDX-License-Identifier: AGPL-3.0-only
// Copyright 2026 Artur Abalov

package dev.sard.server.persistence

import java.time.Clock
import java.util.Random
import java.util.UUID

private const val VERSION_7 = 0x7000L
private const val RAND_A_MASK = 0x0fffL
private const val RAND_B_MASK = 0x3fffffffffffffffL
private const val TIMESTAMP_SHIFT = 16

/** Time-ordered primary keys (RFC 9562 UUIDv7), generated by the application (ADR 0013, rule 6). */
class UuidV7(
    private val clock: Clock,
    private val random: Random,
) {
    fun next(): UUID {
        val high = (clock.millis() shl TIMESTAMP_SHIFT) or VERSION_7 or (random.nextLong() and RAND_A_MASK)
        // Variant 0b10 in the two top bits.
        val low = (random.nextLong() and RAND_B_MASK) or Long.MIN_VALUE
        return UUID(high, low)
    }
}
