// SPDX-License-Identifier: AGPL-3.0-only
// Copyright 2026 Artur Abalov

// Generates src/api/schema.d.ts from the server's OpenAPI document
// (src/api/openapi.json, exported by `make openapi`).
import { readFile, writeFile } from 'node:fs/promises'
import openapiTS, { astToString } from 'openapi-typescript'

const header = `// SPDX-License-Identifier: AGPL-3.0-only
// Copyright 2026 Artur Abalov
// Generated by \`npm run gen:api\` from src/api/openapi.json. Do not edit.

`
const spec = JSON.parse(await readFile(new URL('../src/api/openapi.json', import.meta.url), 'utf8'))
const ast = await openapiTS(spec)
await writeFile(new URL('../src/api/schema.d.ts', import.meta.url), header + astToString(ast))
