// SPDX-License-Identifier: AGPL-3.0-only

// Copyright 2026 Artur Abalov

// Generated from src/routes by @tanstack/router-plugin or `npm run gen:routes`. Do not edit.

/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppTokensRouteImport } from './routes/_app/tokens'
import { Route as AppAgentsIndexRouteImport } from './routes/_app/agents/index'
import { Route as AppAgentsAgentIdRouteImport } from './routes/_app/agents/$agentId'
import { Route as AppRunsIndexRouteImport } from './routes/_app/runs/index'
import { Route as AppRunsRunIdRouteImport } from './routes/_app/runs/$runId'
import { Route as AppSourcesIndexRouteImport } from './routes/_app/sources/index'
import { Route as AppSourcesNewRouteImport } from './routes/_app/sources/new'
import { Route as AppSourcesSourceIdIndexRouteImport } from './routes/_app/sources/$sourceId/index'
import { Route as AppSourcesSourceIdEditRouteImport } from './routes/_app/sources/$sourceId/edit'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppTokensRoute = AppTokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsIndexRoute = AppAgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsAgentIdRoute = AppAgentsAgentIdRouteImport.update({
  id: '/agents/$agentId',
  path: '/agents/$agentId',
  getParentRoute: () => AppRoute,
} as any)
const AppRunsIndexRoute = AppRunsIndexRouteImport.update({
  id: '/runs/',
  path: '/runs/',
  getParentRoute: () => AppRoute,
} as any)
const AppRunsRunIdRoute = AppRunsRunIdRouteImport.update({
  id: '/runs/$runId',
  path: '/runs/$runId',
  getParentRoute: () => AppRoute,
} as any)
const AppSourcesIndexRoute = AppSourcesIndexRouteImport.update({
  id: '/sources/',
  path: '/sources/',
  getParentRoute: () => AppRoute,
} as any)
const AppSourcesNewRoute = AppSourcesNewRouteImport.update({
  id: '/sources/new',
  path: '/sources/new',
  getParentRoute: () => AppRoute,
} as any)
const AppSourcesSourceIdIndexRoute = AppSourcesSourceIdIndexRouteImport.update({
  id: '/sources/$sourceId/',
  path: '/sources/$sourceId/',
  getParentRoute: () => AppRoute,
} as any)
const AppSourcesSourceIdEditRoute = AppSourcesSourceIdEditRouteImport.update({
  id: '/sources/$sourceId/edit',
  path: '/sources/$sourceId/edit',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/settings': typeof AppSettingsRoute
  '/tokens': typeof AppTokensRoute
  '/agents/$agentId': typeof AppAgentsAgentIdRoute
  '/runs/$runId': typeof AppRunsRunIdRoute
  '/sources/new': typeof AppSourcesNewRoute
  '/agents/': typeof AppAgentsIndexRoute
  '/runs/': typeof AppRunsIndexRoute
  '/sources/': typeof AppSourcesIndexRoute
  '/sources/$sourceId/edit': typeof AppSourcesSourceIdEditRoute
  '/sources/$sourceId/': typeof AppSourcesSourceIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/settings': typeof AppSettingsRoute
  '/tokens': typeof AppTokensRoute
  '/': typeof AppIndexRoute
  '/agents/$agentId': typeof AppAgentsAgentIdRoute
  '/runs/$runId': typeof AppRunsRunIdRoute
  '/sources/new': typeof AppSourcesNewRoute
  '/agents': typeof AppAgentsIndexRoute
  '/runs': typeof AppRunsIndexRoute
  '/sources': typeof AppSourcesIndexRoute
  '/sources/$sourceId/edit': typeof AppSourcesSourceIdEditRoute
  '/sources/$sourceId': typeof AppSourcesSourceIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/tokens': typeof AppTokensRoute
  '/_app/': typeof AppIndexRoute
  '/_app/agents/$agentId': typeof AppAgentsAgentIdRoute
  '/_app/runs/$runId': typeof AppRunsRunIdRoute
  '/_app/sources/new': typeof AppSourcesNewRoute
  '/_app/agents/': typeof AppAgentsIndexRoute
  '/_app/runs/': typeof AppRunsIndexRoute
  '/_app/sources/': typeof AppSourcesIndexRoute
  '/_app/sources/$sourceId/edit': typeof AppSourcesSourceIdEditRoute
  '/_app/sources/$sourceId/': typeof AppSourcesSourceIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/setup'
    | '/settings'
    | '/tokens'
    | '/agents/$agentId'
    | '/runs/$runId'
    | '/sources/new'
    | '/agents/'
    | '/runs/'
    | '/sources/'
    | '/sources/$sourceId/edit'
    | '/sources/$sourceId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/setup'
    | '/settings'
    | '/tokens'
    | '/'
    | '/agents/$agentId'
    | '/runs/$runId'
    | '/sources/new'
    | '/agents'
    | '/runs'
    | '/sources'
    | '/sources/$sourceId/edit'
    | '/sources/$sourceId'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/setup'
    | '/_app/settings'
    | '/_app/tokens'
    | '/_app/'
    | '/_app/agents/$agentId'
    | '/_app/runs/$runId'
    | '/_app/sources/new'
    | '/_app/agents/'
    | '/_app/runs/'
    | '/_app/sources/'
    | '/_app/sources/$sourceId/edit'
    | '/_app/sources/$sourceId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tokens': {
      id: '/_app/tokens'
      path: '/tokens'
      fullPath: '/tokens'
      preLoaderRoute: typeof AppTokensRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agents/': {
      id: '/_app/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AppAgentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agents/$agentId': {
      id: '/_app/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AppAgentsAgentIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/runs/': {
      id: '/_app/runs/'
      path: '/runs'
      fullPath: '/runs/'
      preLoaderRoute: typeof AppRunsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/runs/$runId': {
      id: '/_app/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/runs/$runId'
      preLoaderRoute: typeof AppRunsRunIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sources/': {
      id: '/_app/sources/'
      path: '/sources'
      fullPath: '/sources/'
      preLoaderRoute: typeof AppSourcesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sources/new': {
      id: '/_app/sources/new'
      path: '/sources/new'
      fullPath: '/sources/new'
      preLoaderRoute: typeof AppSourcesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sources/$sourceId/': {
      id: '/_app/sources/$sourceId/'
      path: '/sources/$sourceId'
      fullPath: '/sources/$sourceId/'
      preLoaderRoute: typeof AppSourcesSourceIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sources/$sourceId/edit': {
      id: '/_app/sources/$sourceId/edit'
      path: '/sources/$sourceId/edit'
      fullPath: '/sources/$sourceId/edit'
      preLoaderRoute: typeof AppSourcesSourceIdEditRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppSettingsRoute: typeof AppSettingsRoute
  AppTokensRoute: typeof AppTokensRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAgentsAgentIdRoute: typeof AppAgentsAgentIdRoute
  AppRunsRunIdRoute: typeof AppRunsRunIdRoute
  AppSourcesNewRoute: typeof AppSourcesNewRoute
  AppAgentsIndexRoute: typeof AppAgentsIndexRoute
  AppRunsIndexRoute: typeof AppRunsIndexRoute
  AppSourcesIndexRoute: typeof AppSourcesIndexRoute
  AppSourcesSourceIdEditRoute: typeof AppSourcesSourceIdEditRoute
  AppSourcesSourceIdIndexRoute: typeof AppSourcesSourceIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSettingsRoute: AppSettingsRoute,
  AppTokensRoute: AppTokensRoute,
  AppIndexRoute: AppIndexRoute,
  AppAgentsAgentIdRoute: AppAgentsAgentIdRoute,
  AppRunsRunIdRoute: AppRunsRunIdRoute,
  AppSourcesNewRoute: AppSourcesNewRoute,
  AppAgentsIndexRoute: AppAgentsIndexRoute,
  AppRunsIndexRoute: AppRunsIndexRoute,
  AppSourcesIndexRoute: AppSourcesIndexRoute,
  AppSourcesSourceIdEditRoute: AppSourcesSourceIdEditRoute,
  AppSourcesSourceIdIndexRoute: AppSourcesSourceIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
